live_config_reload = true

[colors.bright]
black = "0xa6accd"
blue = "0xadd7ff"
cyan = "0x89ddff"
green = "0x5de4c7"
magenta = "0xfae4fc"
red = "0xd0679d"
white = "0xffffff"
yellow = "0xfffac2"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "0x1b1e28"
blue = "0x89ddff"
cyan = "0xadd7ff"
green = "0x5de4c7"
magenta = "0xfcc5e9"
red = "0xd0679d"
white = "0xffffff"
yellow = "0xfffac2"

[colors.primary]
background = "0x1b1e28"
foreground = "0xa6accd"

[colors.search.focused_match]
background = "0xadd7ff"
foreground = "0x1b1e28"

[colors.search.matches]
background = "0xadd7ff"
foreground = "0x1b1e28"

[colors.selection]
background = "0x303340"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[cursor.style]
blinking = "off"
shape = "underline"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "MonoLisa"
style = "Bold"

[font.bold_italic]
family = "MonoLisa"
style = "Bold Italic"

[font.italic]
family = "MonoLisa"
style = "Medium Italic"

[font.normal]
family = "MonoLisa"
style = "Medium"

[mouse]
hide_when_typing = false

[selection]
save_to_clipboard = true

[window]
decorations = "buttonless"
opacity = 0.95

[window.padding]
x = 24
y = 20
