#!/bin/bash

alias ea="vim $HOME/.config/zsh/aliases"

alias ghostscript="/usr/local/bin/gs"

## vim aliases

## common aliases
alias vi="nvim"
alias vim="nvim"

alias python="python3"
alias pip="pip3"

export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagacad
alias ls="ls -Ap" 
alias ll="ls -lahp"

## git aliases
alias dotfiles="git --git-dir=$HOME/.config/.dotfiles/ --work-tree=$HOME"

alias gu="git undo"

function gc { git commit -m "$@" }
alias gs="git status"
alias gss="git status -s"

alias gcl="git clone"

alias gpush="git push"
alias gpull="git pull"

## custom aliases
function swo {
  cd `find $WORKSPACE -type d -name "$@"`
  oni2 .
  clear
}
function new {
  if [[ -d "$WORKSPACE/$@" ]]
  then
    echo "warning: '$@' already exists."
    echo -n "do you want to go to '$@'? [y/N] "
    read answer
    if [ "$answer" != "y" ]
    then
      return
    fi
    cd "$WORKSPACE/$@"
    clear
  fi
  mkdir "$WORKSPACE/$@"
  if [ $? -ne 0 ]
  then
    echo "error: '$@' could not be created."
    return
  fi
  cd "$WORKSPACE/$@"
  clear
}
function archive {
  mv $@ $WORKSPACE/.archives/
}
alias deleteDSfiles="find . -name '.DS_Store' -type f -delete"

